#!/bin/bash

/etc/init.d/bind9 restart
/etc/init.d/dovecot restart
/etc/init.d/exim restart
/etc/init.d/exim4 restart
/etc/init.d/httpd restart
/etc/init.d/mysqld restart
/etc/init.d/named restart
/etc/init.d/perl-fcgi restart
/etc/init.d/php-fpm56 restart
/etc/init.d/pure-ftpd restart
/etc/init.d/sendmail restart
/etc/init.d/webuzo restart

exit 0